import { useMemo, useState } from 'react';
import { freeChallenges } from './challenges';
import { getCompletedChallenges, saveCompletedChallenges } from './challengeUtils';
import { modules, tools, challengeTitles, methodSteps } from './learningData';

const nav = [['dashboard','Dashboard'],['modules','Modules'],['challenges','60 Challenges'],['tools','Labs & Tools'],['progress','Progress']];

export default function App() {
  const [view,setView]=useState('dashboard');
  const [module,setModule]=useState(null);
  const [tool,setTool]=useState(null);
  const [completed,setCompleted]=useState(getCompletedChallenges);
  const [open,setOpen]=useState({});
  const freeById=useMemo(()=>new Map(freeChallenges.map(c=>[`DSP-${String(c.id).padStart(3,'0')}`,c])),[]);
  const done=completed.length;
  const percent=Math.round(done/60*100);
  const go=v=>{setView(v);setModule(null);setTool(null)};
  const openModule=m=>{setModule(m);setTool(null);setView('module')};
  const openTool=t=>{setTool(t);setModule(null);setView('tool')};
  const toggle=id=>{const next=completed.includes(id)?completed.filter(x=>x!==id):[...completed,id];setCompleted(next);saveCompletedChallenges(next)};
  const moduleDone=m=>{const first=Number(m.range.match(/DSP-(\d+)/)?.[1]||1);return Array.from({length:m.count},(_,i)=>`DSP-${String(first+i).padStart(3,'0')}`).filter(id=>completed.includes(id)).length};
  return <div className="app-shell"><aside className="sidebar"><button className="brand brand-button" onClick={()=>go('dashboard')}><span className="brand-mark">D</span><span>DevSprint</span></button><div className="side-label">LEARNING SPACE</div><nav className="side-nav">{nav.map(([id,label])=><button key={id} className={view===id||(id==='modules'&&view==='module')||(id==='tools'&&view==='tool')?'active':''} onClick={()=>go(id)}><span>{id==='dashboard'?'⌂':id==='modules'?'▦':id==='challenges'?'◇':id==='tools'?'⚙':'◔'}</span>{label}</button>)}</nav><div className="sidebar-progress"><span>Your progress</span><strong>{done}/60</strong><div className="progress-track"><div className="progress-fill" style={{width:`${percent}%`}}/></div><small>{percent}% complete</small></div><div className="sidebar-note">V1 · JavaScript Problem-Solving &amp; DSA Toolkit</div></aside><main className="learning-main"><header className="topbar"><div><span className="mobile-brand">DEVSPRINT</span><span className="breadcrumb">Learning space / {view==='module'?module?.title:view==='tool'?tool?.title:view==='progress'?'Progress':view==='tools'?'Labs & Tools':view==='challenges'?'Challenges':'Dashboard'}</span></div><div className="top-progress"><span>{done} completed</span><div className="mini-progress"><div style={{width:`${percent}%`}}/></div></div></header>{view==='dashboard'&&<Dashboard modules={modules} tools={tools} done={done} percent={percent} onModule={openModule} onTool={openTool} onView={go}/>} {view==='modules'&&<Modules modules={modules} moduleDone={moduleDone} onModule={openModule}/>} {view==='module'&&module&&<ModuleDetail module={module} completed={completed} moduleDone={moduleDone(module)} titles={challengeTitles} freeById={freeById} open={open} setOpen={setOpen} back={()=>go('modules')} challenges={()=>go('challenges')}/>} {view==='challenges'&&<Challenges titles={challengeTitles} freeById={freeById} completed={completed} open={open} setOpen={setOpen} toggle={toggle}/>} {view==='tools'&&<Tools tools={tools} onTool={openTool}/>} {view==='tool'&&tool&&<ToolDetail tool={tool} back={()=>go('tools')} project={()=>openModule(modules[7])}/>} {view==='progress'&&<Progress modules={modules} moduleDone={moduleDone} done={done} percent={percent} onModule={openModule}/>}</main></div>;
}

function Dashboard({modules,tools,done,percent,onModule,onTool,onView}){return <Page><section className="welcome"><div><span className="eyebrow">DEVSPRINT LEARNING SPACE</span><h1>Build the habit of <span>solving problems.</span></h1><p>Learn the full loop: understand, break down, design, implement, test, debug, analyze, and improve.</p></div><div className="hero-progress"><div className="ring" style={{background:`conic-gradient(#8fd3ff ${percent}%,#202a38 0)`}}><strong>{percent}%</strong></div><span>course progress</span></div></section><section className="stats-grid"><Stat value="8" label="Modules"/><Stat value="60" label="Challenges"/><Stat value="4" label="Practice tools"/><Stat value={done} label="Completed"/></section><section className="continue-card"><div><span className="section-label">START HERE</span><h2>Module 1 · Think Like a Programmer</h2><p>Start with reasoning before syntax.</p></div><button className="button primary" onClick={()=>onModule(modules[0])}>Start learning →</button></section><SectionHeader title="Your curriculum" action="View all modules" onAction={()=>onView('modules')}/><div className="module-grid">{modules.map(m=><ModuleCard key={m.id} module={m} completed={0} onClick={()=>onModule(m)}/>)}</div><SectionHeader title="Practice tools" action="Open tools" onAction={()=>onView('tools')}/><div className="tool-grid">{tools.map(t=><ToolCard key={t.id} tool={t} onClick={()=>onTool(t)}/>)}</div></Page>}

function Modules({modules,moduleDone,onModule}){return <Page><PageIntro label="CURRICULUM" title="Eight modules. One repeatable system." text="Each module now contains a learning roadmap, lessons, challenge range, and practice path."/><div className="method-strip">{methodSteps.map(x=><div key={x[0]}><b>{x[0]}</b><strong>{x[1]}</strong><span>{x[2]}</span></div>)}</div><div className="module-grid large">{modules.map(m=><ModuleCard key={m.id} module={m} completed={moduleDone(m)} onClick={()=>onModule(m)}/>)}</div></Page>}

function ModuleDetail({module,completed,moduleDone,titles,freeById,open,setOpen,back,challenges}){const first=Number(module.range.match(/DSP-(\d+)/)?.[1]||1);const items=titles.slice(first-1,first-1+module.count);return <Page><button className="back-button" onClick={back}>← Back to modules</button><section className="module-hero"><div><span className="module-number">MODULE {module.number}</span><h1>{module.title}</h1><p>{module.description}</p></div><div className="module-score"><strong>{moduleDone}/{module.count}</strong><span>challenges completed</span><div className="progress-track"><div className="progress-fill" style={{width:`${moduleDone/module.count*100}%`}}/></div></div></section><div className="focus-line"><strong>Focus</strong><span>{module.focus}</span><span>{module.range}</span></div><section className="lesson-roadmap"><span className="section-label">LESSONS</span><div className="lesson-grid">{module.lessons.map((l,i)=><article className="lesson-card" key={l}><span>LESSON {i+1}</span><strong>{l}</strong><p>Understand the concept, explain it, then apply it to a challenge.</p></article>)}</div></section><section className="lesson-roadmap"><span className="section-label">MODULE WORKFLOW</span><div className="roadmap"><b>Learn</b><i>→</i><b>Attempt</b><i>→</i><b>Test</b><i>→</i><b>Debug</b><i>→</i><b>Analyze</b><i>→</i><b>Improve</b></div><p>Free challenges are interactive here. The complete paid workbook is delivered with the customer product.</p></section><SectionHeader title={`${module.count} challenges`} action="Open challenge browser" onAction={challenges}/><div className="challenge-index">{items.map((title,i)=>{const n=first+i,id=`DSP-${String(n).padStart(3,'0')}`,free=freeById.get(id);return <ChallengeRow key={id} id={id} title={title} completed={completed.includes(id)} free={!!free} onClick={()=>free&&setOpen(x=>({...x,[id]:!x[id]}))}/>})}</div></Page>}

function Challenges({titles,freeById,completed,open,setOpen,toggle}){return <Page><PageIntro label="PRACTICE" title="60 challenges. Not 60 decorative boxes." text="The first 10 are interactive on the public site. The remaining 50 are mapped to the paid toolkit so the curriculum structure is visible without publishing the customer workbook."/><div className="challenge-toolbar"><span>{completed.length}/60 completed</span><span>10 interactive</span><span>50 toolkit</span></div><div className="challenge-browser">{titles.map(c=>{const free=freeById.get(c.id),isDone=completed.includes(c.id);return <div key={c.id} className={`browser-row ${open[c.id]?'open':''}`}><button className="browser-main" disabled={!free} onClick={()=>setOpen(x=>({...x,[c.id]:!x[c.id]}))}><span className="browser-id">{c.id}</span><strong>{c.title}</strong><span className={`access-pill ${free?'free':''}`}>{free?'FREE':'TOOLKIT'}</span><span className="completion-state">{isDone?'✓':'○'}</span></button>{open[c.id]&&free&&<FreeChallenge challenge={free} done={isDone} toggle={toggle}/>}</div>})}</div></Page>}

function FreeChallenge({challenge,done,toggle}){const id=`DSP-${String(challenge.id).padStart(3,'0')}`;return <div className="free-challenge-detail"><p><b>Problem:</b> {challenge.prompt}</p><code>{challenge.example}</code><div className="hint-box"><b>Hint:</b> {challenge.hint}</div><div className="challenge-actions"><button className="button secondary" onClick={()=>alert(challenge.solution)}>Show solution</button><button className="button primary" onClick={()=>toggle(id)}>{done?'Mark incomplete':'Mark complete'}</button></div></div>}

function Tools({tools,onTool}){return <Page><PageIntro label="LABS & TOOLS" title="Practice beyond the lesson." text="Open a real workspace instead of staring at a card pretending it is a feature."/><div className="tool-grid large">{tools.map(t=><ToolCard key={t.id} tool={t} onClick={()=>onTool(t)}/>)}</div><section className="tools-method"><span className="section-label">THE FULL LOOP</span><div className="roadmap"><b>Learn</b><i>→</i><b>Attempt</b><i>→</i><b>Test</b><i>→</i><b>Debug</b><i>→</i><b>Explain</b><i>→</i><b>Revise</b></div></section></Page>}

function ToolDetail({tool,back,project}){return <Page><button className="back-button" onClick={back}>← Back to labs &amp; tools</button><PageIntro label={tool.status.toUpperCase()} title={tool.title} text={tool.description}/><section className="lesson-roadmap"><span className="section-label">WORKSPACE</span>{tool.prompt&&<div className="hint-box"><b>Task</b><p>{tool.prompt}</p></div>}{tool.buggyCode&&<div className="code-compare"><div><span className="section-label">BUG</span><pre><code>{tool.buggyCode}</code></pre></div><div><span className="section-label">FIX</span><pre><code>{tool.fix}</code></pre></div></div>}{tool.steps&&<div className="tool-steps">{tool.steps.map((s,i)=><div key={s}><span>{String(i+1).padStart(2,'0')}</span><strong>{s}</strong></div>)}</div>}{tool.id==='project'&&<button className="button primary" onClick={project}>Open Module 8 project →</button>}</section></Page>}

function Progress({modules,moduleDone,done,percent,onModule}){return <Page><PageIntro label="PROGRESS" title="Your learning, in one place." text="Completion is saved in your browser. Use it as evidence of practice, not as a substitute for actually understanding the solution."/><section className="stats-grid"><Stat value={`${done}/60`} label="Challenges completed"/><Stat value={`${percent}%`} label="Overall progress"/><Stat value={modules.filter(m=>moduleDone(m)===m.count).length} label="Modules finished"/><Stat value={60-done} label="Remaining"/></section><div className="progress-module-list">{modules.map(m=>{const d=moduleDone(m);return <button className="progress-module" key={m.id} onClick={()=>onModule(m)}><div><span>MODULE {m.number}</span><strong>{m.title}</strong></div><div className="progress-module-right"><b>{d}/{m.count}</b><div className="progress-track"><div className="progress-fill" style={{width:`${d/m.count*100}%`}}/></div></div></button>})}</div></Page>}

function Page({children}){return <div className="page">{children}</div>}
function PageIntro({label,title,text}){return <section className="page-intro"><span className="eyebrow">{label}</span><h1>{title}</h1><p>{text}</p></section>}
function SectionHeader({title,action,onAction}){return <div className="section-header"><h2>{title}</h2><button onClick={onAction}>{action} →</button></div>}
function Stat({value,label}){return <div className="stat"><strong>{value}</strong><span>{label}</span></div>}
function ModuleCard({module,completed,onClick}){return <button className="module-card" onClick={onClick}><div className="module-card-top"><span>{module.number}</span><span>{completed}/{module.count}</span></div><h3>{module.title}</h3><p>{module.description}</p><div className="card-meta"><span>{module.count} challenges</span><span>{module.range}</span></div><div className="card-arrow">→</div></button>}
function ToolCard({tool,onClick}){return <button className="tool-card clickable" onClick={onClick}><span className="tool-icon">{tool.icon}</span><div><span className="tool-status">{tool.status}</span><h3>{tool.title}</h3><p>{tool.description}</p></div><span className="card-arrow">→</span></button>}
function ChallengeRow({id,title,completed,free,onClick}){return <button className="challenge-row" onClick={onClick} disabled={!free}><span className="browser-id">{id}</span><strong>{title}</strong><span className={`access-pill ${free?'free':''}`}>{free?'FREE':'TOOLKIT'}</span><span className="completion-state">{completed?'✓':'○'}</span></button>}
