export const freeChallenges = [
  {
    id: 1,
    title: 'Find the Largest Number',
    difficulty: '1 · Basic',
    skill: 'Arrays + iteration',
    prompt: 'Given an array of numbers, return the largest value without sorting the array.',
    example: '[8, 3, 15, 6, 10] → 15',
    hint: 'Keep one value as your current largest, then compare every remaining value to it.',
    pseudocode: ['Start with the first number as largest.', 'Visit each remaining number.', 'If it is larger than largest, replace largest.', 'Return largest.'],
    solution: `function findLargest(numbers) {\n  let largest = numbers[0];\n\n  for (let i = 1; i < numbers.length; i++) {\n    if (numbers[i] > largest) largest = numbers[i];\n  }\n\n  return largest;\n}`,
    tests: ['findLargest([8, 3, 15, 6, 10]) → 15', 'findLargest([5]) → 5', 'findLargest([-4, -9, -2]) → -2', 'findLargest([0, -1, -3]) → 0'],
    complexity: 'Time: O(n) · Space: O(1)',
  },
  {
    id: 2,
    title: 'Count Even Numbers',
    difficulty: '1 · Basic',
    skill: 'Arrays + conditions',
    prompt: 'Return how many numbers in an array are even.',
    example: '[2, 7, 4, 9, 10] → 3',
    hint: 'An even number has a remainder of 0 when divided by 2.',
    pseudocode: ['Start count at 0.', 'Visit every number.', 'If number % 2 equals 0, increase count.', 'Return count.'],
    solution: `function countEven(numbers) {\n  let count = 0;\n\n  for (const number of numbers) {\n    if (number % 2 === 0) count++;\n  }\n\n  return count;\n}`,
    tests: ['countEven([2, 7, 4, 9, 10]) → 3', 'countEven([]) → 0', 'countEven([1, 3, 5]) → 0', 'countEven([-4, -3, 0, 2]) → 3'],
    complexity: 'Time: O(n) · Space: O(1)',
  },
  {
    id: 3,
    title: 'Reverse a String',
    difficulty: '1 · Basic',
    skill: 'Strings + iteration',
    prompt: 'Return a string with its characters in reverse order without using reverse().',
    example: '"devsprint" → "tnirpsved"',
    hint: 'Walk through the characters from the end toward the beginning.',
    pseudocode: ['Start with an empty result.', 'Start at the final character.', 'Add each character to result while moving backward.', 'Return result.'],
    solution: `function reverseString(text) {\n  let result = '';\n\n  for (let i = text.length - 1; i >= 0; i--) {\n    result += text[i];\n  }\n\n  return result;\n}`,
    tests: ['reverseString("devsprint") → "tnirpsved"', 'reverseString("") → ""', 'reverseString("a") → "a"', 'reverseString("DevSprint") → "tnirpSveD"'],
    complexity: 'Time: O(n) · Space: O(n)',
  },
  {
    id: 4,
    title: 'Sum Positive Numbers',
    difficulty: '2 · Beginner',
    skill: 'Arrays + conditions',
    prompt: 'Return the sum of all positive numbers in an array. Ignore zero and negative values.',
    example: '[-2, 5, 7, -1, 3] → 15',
    hint: 'Keep a running total and add a value only when it is greater than zero.',
    pseudocode: ['Start total at 0.', 'Visit every number.', 'If it is positive, add it to total.', 'Return total.'],
    solution: `function sumPositive(numbers) {\n  let total = 0;\n\n  for (const number of numbers) {\n    if (number > 0) total += number;\n  }\n\n  return total;\n}`,
    tests: ['sumPositive([-2, 5, 7, -1, 3]) → 15', 'sumPositive([-4, 0]) → 0', 'sumPositive([2]) → 2', 'sumPositive([1, -1, 0, 3]) → 4'],
    complexity: 'Time: O(n) · Space: O(1)',
  },
  {
    id: 5,
    title: 'Find First Matching Value',
    difficulty: '2 · Beginner',
    skill: 'Linear search',
    prompt: 'Return the index of the first value that matches the target, or -1 if it is not found.',
    example: '[4, 8, 2, 8], 8 → 1',
    hint: 'Scan from left to right and stop immediately when the target is found.',
    pseudocode: ['Start at index 0.', 'Compare each value with target.', 'Return the current index on the first match.', 'Return -1 if no match exists.'],
    solution: `function findFirst(numbers, target) {\n  for (let i = 0; i < numbers.length; i++) {\n    if (numbers[i] === target) return i;\n  }\n\n  return -1;\n}`,
    tests: ['findFirst([4, 8, 2, 8], 8) → 1', 'findFirst([1, 2, 3], 9) → -1', 'findFirst([], 1) → -1', 'findFirst([7, 2, 7], 7) → 0'],
    complexity: 'Time: O(n) · Space: O(1)',
  },
  {
    id: 6,
    title: 'Remove Duplicates',
    difficulty: '3 · Intermediate',
    skill: 'Arrays + Set',
    prompt: 'Return a new array containing each value only once while preserving first-seen order.',
    example: '[3, 3, 1, 2, 1] → [3, 1, 2]',
    hint: 'A Set can remember which values have already appeared.',
    pseudocode: ['Create an empty Set and result array.', 'Visit each value.', 'If the Set does not contain it, add it to both.', 'Return result.'],
    solution: `function removeDuplicates(numbers) {\n  const seen = new Set();\n  const result = [];\n\n  for (const number of numbers) {\n    if (!seen.has(number)) {\n      seen.add(number);\n      result.push(number);\n    }\n  }\n\n  return result;\n}`,
    tests: ['removeDuplicates([3, 3, 1, 2, 1]) → [3, 1, 2]', 'removeDuplicates([]) → []', 'removeDuplicates([5, 5, 5]) → [5]', 'removeDuplicates([2, 3, 2, 4]) → [2, 3, 4]'],
    complexity: 'Time: O(n) average · Space: O(n)',
  },
  {
    id: 7,
    title: 'Check Palindrome',
    difficulty: '3 · Intermediate',
    skill: 'Strings + two pointers',
    prompt: 'Return true when a string reads the same forward and backward. Treat uppercase and lowercase as the same.',
    example: '"Level" → true',
    hint: 'Compare characters from both ends while moving toward the center.',
    pseudocode: ['Normalize the string.', 'Set left at the beginning and right at the end.', 'Compare both characters.', 'Move inward until they meet.'],
    solution: `function isPalindrome(text) {\n  const value = text.toLowerCase();\n  let left = 0;\n  let right = value.length - 1;\n\n  while (left < right) {\n    if (value[left] !== value[right]) return false;\n    left++;\n    right--;\n  }\n\n  return true;\n}`,
    tests: ['isPalindrome("Level") → true', 'isPalindrome("hello") → false', 'isPalindrome("") → true', 'isPalindrome("RaceCar") → true'],
    complexity: 'Time: O(n) · Space: O(n) for normalized text',
  },
  {
    id: 8,
    title: 'Second Largest Distinct Number',
    difficulty: '3 · Intermediate',
    skill: 'Arrays + state tracking',
    prompt: 'Return the second largest distinct number. Return null when fewer than two distinct values exist.',
    example: '[10, 4, 10, 7, 8] → 8',
    hint: 'Track the largest and second-largest distinct values without sorting.',
    pseudocode: ['Start largest and second as empty.', 'Visit each number.', 'Ignore a number equal to largest.', 'Update largest and second when appropriate.', 'Return second or null.'],
    solution: `function secondLargest(numbers) {\n  let largest;\n  let second;\n\n  for (const number of numbers) {\n    if (number === largest) continue;\n\n    if (largest === undefined || number > largest) {\n      second = largest;\n      largest = number;\n    } else if (second === undefined || number > second) {\n      second = number;\n    }\n  }\n\n  return second === undefined ? null : second;\n}`,
    tests: ['secondLargest([10, 4, 10, 7, 8]) → 8', 'secondLargest([5, 5]) → null', 'secondLargest([-2, -8, -4]) → -4', 'secondLargest([0, -1]) → -1', 'secondLargest([0, 0, -2]) → -2', 'secondLargest([]) → null'],
    complexity: 'Time: O(n) · Space: O(1)',
  },
  {
    id: 9,
    title: 'Balanced Parentheses',
    difficulty: '3 · Intermediate',
    skill: 'Stack + validation',
    prompt: 'Determine whether parentheses are correctly opened and closed in a string.',
    example: '"(()())" → true',
    hint: 'Every opening parenthesis must be remembered until its matching closing parenthesis appears. A stack is a natural fit.',
    pseudocode: ['Create an empty stack.', 'Push every opening parenthesis.', 'For a closing parenthesis, reject if the stack is empty, otherwise pop.', 'Accept only when the stack is empty at the end.'],
    solution: `function isBalanced(text) {\n  const stack = [];\n\n  for (const char of text) {\n    if (char === '(') stack.push(char);\n    else if (char === ')') {\n      if (stack.length === 0) return false;\n      stack.pop();\n    }\n  }\n\n  return stack.length === 0;\n}`,
    tests: ['isBalanced("(()())") → true', 'isBalanced("(()") → false', 'isBalanced(")(") → false', 'isBalanced("") → true', 'isBalanced("()()") → true', 'isBalanced("())(") → false'],
    complexity: 'Time: O(n) · Space: O(n)',
  },
  {
    id: 10,
    title: 'Two Sum',
    difficulty: '3 · Intermediate',
    skill: 'Hash map + optimization',
    prompt: 'Return the indices of two numbers whose sum equals the target. Assume one valid answer exists.',
    example: '[2, 7, 11, 15], 9 → [0, 1]',
    hint: 'For each value, calculate the complement needed to reach the target and check previously seen values.',
    pseudocode: ['Create a Map of value → index.', 'For each number, calculate target - number.', 'If the complement exists, return its index and current index.', 'Otherwise store the current value and index.', 'Return [] if no pair exists.'],
    solution: `function twoSum(numbers, target) {\n  const seen = new Map();\n\n  for (let i = 0; i < numbers.length; i++) {\n    const needed = target - numbers[i];\n\n    if (seen.has(needed)) return [seen.get(needed), i];\n    seen.set(numbers[i], i);\n  }\n\n  return [];\n}`,
    tests: ['twoSum([2, 7, 11, 15], 9) → [0, 1]', 'twoSum([3, 2, 4], 6) → [1, 2]', 'twoSum([3, 3], 6) → [0, 1]', 'twoSum([1, 5], 10) → []', 'twoSum([-3, 4, 2, 7], 1) → [0, 1]'],
    complexity: 'Time: O(n) average · Space: O(n)',
  },
];
