export const freeChallenges = [
  {
    id: 1,
    title: 'Find the Largest Number',
    difficulty: '1 · Basic',
    skill: 'Arrays + iteration',
    prompt: 'Given an array of numbers, return the largest value without sorting the array.',
    example: '[8, 3, 15, 6, 10] → 15',
    hint: 'Keep one value as your current largest, then compare every remaining value to it.',
  },
  {
    id: 2,
    title: 'Count Even Numbers',
    difficulty: '1 · Basic',
    skill: 'Arrays + conditions',
    prompt: 'Return how many numbers in an array are even.',
    example: '[2, 7, 4, 9, 10] → 3',
    hint: 'An even number has a remainder of 0 when divided by 2.',
  },
  {
    id: 3,
    title: 'Reverse a String',
    difficulty: '1 · Basic',
    skill: 'Strings + iteration',
    prompt: 'Return a string with its characters in reverse order without using reverse().',
    example: '"devsprint" → "tnirpsved"',
    hint: 'Walk through the characters from the end toward the beginning.',
  },
  {
    id: 4,
    title: 'Find the First Duplicate',
    difficulty: '2 · Beginner',
    skill: 'Arrays + sets',
    prompt: 'Return the first value that appears more than once. Return null if every value is unique.',
    example: '[4, 2, 7, 2, 9] → 2',
    hint: 'Track values you have already seen.',
  },
  {
    id: 5,
    title: 'Count Vowels',
    difficulty: '2 · Beginner',
    skill: 'Strings + conditions',
    prompt: 'Count the vowels in a string. Treat uppercase and lowercase letters the same.',
    example: '"JavaScript" → 3',
    hint: 'Normalize the input first, then check each character against the vowel set.',
  },
  {
    id: 6,
    title: 'Linear Search',
    difficulty: '2 · Beginner',
    skill: 'Searching + Big-O',
    prompt: 'Return the index of a target value in an array, or -1 when it is not present.',
    example: '[5, 8, 2, 9], 2 → 2',
    hint: 'Check values one by one from the start.',
  },
  {
    id: 7,
    title: 'Remove Duplicates',
    difficulty: '3 · Intermediate',
    skill: 'Arrays + data structures',
    prompt: 'Return a new array containing each value only once while preserving first-seen order.',
    example: '[3, 3, 1, 2, 1] → [3, 1, 2]',
    hint: 'A Set can remember which values have already appeared.',
  },
  {
    id: 8,
    title: 'Balanced Brackets',
    difficulty: '3 · Intermediate',
    skill: 'Stack + validation',
    prompt: 'Determine whether (), [], and {} are correctly opened and closed.',
    example: '"{[()]}" → true',
    hint: 'A stack is useful because the most recently opened bracket must close first.',
  },
  {
    id: 9,
    title: 'Two Sum',
    difficulty: '3 · Intermediate',
    skill: 'Hash map + optimization',
    prompt: 'Return the indices of two numbers whose sum equals the target. Assume one valid answer exists.',
    example: '[2, 7, 11, 15], 9 → [0, 1]',
    hint: 'Ask what number you need to complete the target and remember values already visited.',
  },
  {
    id: 10,
    title: 'Student Performance Analyzer',
    difficulty: '4 · Challenging',
    skill: 'Arrays + sorting + analysis',
    prompt: 'Given student names and scores, calculate average, highest, lowest, pass/fail counts, and a ranking.',
    example: 'A small dataset → summary + ranked students',
    hint: 'Break the project into small functions. Solve one requirement, test it, then move to the next.',
  },
];
